Repository anliben/sport-player, pull requests merged in 2022-05, with the labels that each got.

#65 [feature] Modal Truco
  src/app/pages/mesa/cashgame1x1/cashgame1x1.page.ts
  src/app/pages/mesa/cashgame2x2/cashgame2x2.page.html
  src/app/pages/mesa/cashgame2x2/cashgame2x2.page.ts
Labels: feature

#66 Criar o modal de sinal secreto.
  src/app/app-routing.module.ts
  src/app/pages/mesa/cashgame1x1/cashgame1x1.page.ts
  src/app/pages/mesa/cashgame2x2/cashgame2x2.page.html
  src/app/pages/mesa/cashgame2x2/cashgame2x2.page.ts
  src/app/shared/components/modais/sinal-secreto-modal/sinal-secreto-modal-routing.module.ts
  src/app/shared/components/modais/sinal-secreto-modal/sinal-secreto-modal.module.ts
  src/app/shared/components/modais/sinal-secreto-modal/sinal-secreto-modal.page.html
  src/app/shared/components/modais/sinal-secreto-modal/sinal-secreto-modal.page.scss
  src/app/shared/components/modais/sinal-secreto-modal/sinal-secreto-modal.page.spec.ts
  src/app/shared/components/modais/sinal-secreto-modal/sinal-secreto-modal.page.ts
  src/global.scss
Labels: fix, feature

#75 [feature]: Criar modal de configuração do jogo
  src/app/app-routing.module.ts
  src/app/pages/mesa/cashgame1x1/cashgame1x1.page.html
  src/app/pages/mesa/cashgame1x1/cashgame1x1.page.ts
  src/app/pages/mesa/cashgame2x2/cashgame2x2.page.html
  src/app/pages/mesa/cashgame2x2/cashgame2x2.page.ts
  src/app/pages/mesa/mesa.page.ts
  src/app/shared/components/config-jogo-item/config-jogo-item.component.html
  src/app/shared/components/config-jogo-item/config-jogo-item.component.scss
  src/app/shared/components/config-jogo-item/config-jogo-item.component.spec.ts
  src/app/shared/components/config-jogo-item/config-jogo-item.component.ts
  src/app/shared/components/configuracao-jogo-modal/configuracao-jogo-modal.component.html
  src/app/shared/components/modais/configuracao-jogo-modal/configuracao-jogo-modal.component.html
  src/app/shared/components/modais/configuracao-jogo-modal/configuracao-jogo-modal.component.scss
  src/app/shared/components/modais/configuracao-jogo-modal/configuracao-jogo-modal.component.spec.ts
  src/app/shared/components/modais/configuracao-jogo-modal/configuracao-jogo-modal.component.ts
  src/app/shared/components/modais/sinal-secreto-modal/sinal-secreto-modal.page.html
  src/app/shared/components/modais/sinal-secreto-modal/sinal-secreto-modal.page.scss
  src/app/shared/shared.module.ts
  src/global.scss
Labels: feature

#74 [feature] Modal de pagamento
  src/app/pages/clube/perfil-jogador/perfil-jogador.component.html
  src/app/shared/components/modais/adicionar-fichas-modal/adicionar-fichas-modal.component.html
  src/app/shared/components/modais/adicionar-fichas-modal/adicionar-fichas-modal.component.scss
  src/app/shared/components/modais/adicionar-fichas-modal/adicionar-fichas-modal.component.ts
  src/app/shared/components/modais/pagamento-modal/pagamento-modal.component.html
  src/app/shared/components/modais/pagamento-modal/pagamento-modal.component.scss
  src/app/shared/components/modais/pagamento-modal/pagamento-modal.component.spec.ts
  src/app/shared/components/modais/pagamento-modal/pagamento-modal.component.ts
  src/app/shared/shared.module.ts
  src/global.scss
Labels: feature

#85 [feature full]: Implementando andamento historico de cartas / detalhes do jogo no cashgame / modal de confirmar comprar / melhorias no desgin
  src/app/interfaces/item-store-interface.ts
  src/app/pages/clube/clube.page.html
  src/app/pages/clube/clube.page.ts
  src/app/pages/clube/perfil-jogador/perfil-jogador.component.html
  src/app/pages/clube/perfil-jogador/perfil-jogador.component.ts
  src/app/pages/home/home.page.html
  src/app/pages/home/play/play.page.html
  src/app/pages/home/store/store.page.html
  src/app/pages/home/store/store.page.scss
  src/app/pages/home/store/store.page.ts
  src/app/pages/mesa/cashgame1x1/cashgame1x1.page.html
  src/app/pages/mesa/cashgame1x1/cashgame1x1.page.ts
  src/app/pages/mesa/cashgame2x2/cashgame2x2.page.html
  src/app/pages/mesa/cashgame2x2/cashgame2x2.page.ts
  src/app/pages/trucco/trucco.page.html
  src/app/pages/trucco/trucco.page.scss
  src/app/shared/components/header/header.component.html
  src/app/shared/components/mesas/mesas.component.html
  src/app/shared/components/modais/confirmar-compra-item-modal/confirmar-compra-item-modal.component.html
  src/app/shared/components/modais/confirmar-compra-item-modal/confirmar-compra-item-modal.component.scss
  src/app/shared/components/modais/confirmar-compra-item-modal/confirmar-compra-item-modal.component.spec.ts
  src/app/shared/components/modais/confirmar-compra-item-modal/confirmar-compra-item-modal.component.ts
  src/app/shared/components/modais/detalhes-jogo-cashgame-modal/detalhes-jogo-cashgame-modal.component.html
  src/app/shared/components/modais/detalhes-jogo-cashgame-modal/detalhes-jogo-cashgame-modal.component.scss
  src/app/shared/components/modais/detalhes-jogo-cashgame-modal/detalhes-jogo-cashgame-modal.component.spec.ts
  src/app/shared/components/modais/detalhes-jogo-cashgame-modal/detalhes-jogo-cashgame-modal.component.ts
  src/app/shared/components/modais/historico-maos-modal/historico-maos-modal.component.html
  src/app/shared/components/modais/historico-maos-modal/historico-maos-modal.component.scss
  src/app/shared/components/modais/historico-maos-modal/historico-maos-modal.component.spec.ts
  src/app/shared/components/modais/historico-maos-modal/historico-maos-modal.component.ts
  src/app/shared/components/perfil/perfil.component.html
  src/app/shared/shared.module.ts
  src/assets/game/game/seta-tab.png
  src/global.scss
Labels: bug, wontfix, fix, feature
